---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, nfsv3 
summary: Estas limitaciones conocidas son específicas de Cloud Volumes ONTAP en Microsoft Azure. 
---
= Limitaciones conocidas de Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las siguientes limitaciones conocidas son específicas de Cloud Volumes ONTAP en Microsoft Azure. No olvide revisar también link:reference-limitations.html["Limitaciones en todos los proveedores de cloud"].



== Limitaciones del uso de extensiones de Azure VM

Cloud Volumes ONTAP no es compatible con las extensiones de máquinas virtuales de Azure ni con aplicaciones de máquinas virtuales en una implementación. El uso de Cloud Volumes ONTAP en Azure con extensiones de VM provoca retrasos en las operaciones y NetApp recomienda evitarlos.



== No se admiten nuevas implementaciones

Las nuevas implementaciones de Cloud Volumes ONTAP 9.6 ya no son compatibles con Azure. Deberá poner en marcha Cloud Volumes ONTAP 9.7.



== Limitaciones de ALTA DISPONIBILIDAD

Las siguientes limitaciones afectan a los pares de alta disponibilidad de Cloud Volumes ONTAP en Microsoft Azure:

* NFSv4 no es compatible. NFSv3 es compatible.
* En algunas regiones no se admiten pares DE HA.
+
https://cloud.netapp.com/cloud-volumes-global-regions["Consulte la lista de regiones de Azure admitidas"^]


