---
sidebar: sidebar 
permalink: reference-configs-azure.html 
keywords: vm, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations, disks, sizes 
summary: Cloud Volumes ONTAP está disponible en Azure con las configuraciones de PAYGO y BYOL. Para PAYGO, puede elegir entre explorar, Estándar o Premium. 
---
= Configuraciones compatibles en Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP está disponible en Azure con dos opciones de precios: De pago por uso y con su propia licencia (BYOL). En el modelo de pago por uso, puede elegir entre tres configuraciones: Explorar, Standard o Premium.



== Configuraciones admitidas por licencia

Cloud Volumes ONTAP está disponible en Azure como un único sistema de nodo y como par de nodos de alta disponibilidad para tolerancia a fallos y operaciones no disruptivas.

No se admite la actualización de un sistema de un solo nodo a un par de alta disponibilidad. Si desea cambiar entre un sistema de un solo nodo y un par de alta disponibilidad, debe poner en marcha un sistema nuevo y replicar los datos desde el sistema existente al nuevo sistema.



=== Sistemas de un solo nodo

Puede elegir entre las siguientes configuraciones al poner en marcha Cloud Volumes ONTAP como un sistema de un solo nodo en Azure:

[cols="h,d,d,d,d"]
|===
|  | Explorar | Estándar | Premium | BYOL 


| Tipos de máquina virtual admitidos | DS3_v2  a| 
* DS4_v2
* DS13_v2

 a| 
* DS5_v2
* DS14_v2
* DS15_v2

 a| 
* DS3_v2
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2
* DS15_v2




| Tipos de disco compatibles hacia esta 1 4+| Discos duros estándar gestionados, discos SSD estándar gestionados y discos SSD premium gestionados 


| Organización en niveles de datos inactivos para el almacenamiento BLOB | No admitido 3+| Compatible 


| Capacidad máxima del sistema (discos + almacenamiento de objetos) | 2 TIB | 10 TIB | 368 TIB | 368 TIB por licencia 
|===
Notas:

. El rendimiento de escritura mejorado se habilita cuando se utilizan unidades SSD, pero no cuando se utiliza el tipo de máquina virtual DS3_v2.
. Para obtener información sobre la compatibilidad con Azure region, consulte https://cloud.netapp.com/cloud-volumes-global-regions["Regiones globales de Cloud Volumes"^].




=== Parejas de HA

Puede elegir entre las siguientes configuraciones al poner en marcha Cloud Volumes ONTAP como pareja de alta disponibilidad en Azure:

[cols="h,d,d,d,d"]
|===
|  | Explorar | Estándar | Premium | BYOL 


| Tipos de máquina virtual admitidos | No admitido  a| 
* DS4_v2
* DS13_v2

 a| 
* DS5_v2
* DS14_v2
* DS15_v2

 a| 
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2
* DS15_v2




| Tipos de disco admitidos | No admitido 3+| Blobs de página premium 


| Organización en niveles de datos inactivos para el almacenamiento BLOB | No admitido 3+| Compatible 


| Capacidad máxima del sistema (discos + almacenamiento de objetos) | No admitido | 10 TIB | 368 TIB | 368 TIB por licencia 
|===
Notas:

. Para obtener información sobre la compatibilidad con Azure region, consulte https://cloud.netapp.com/cloud-volumes-global-regions["Regiones globales de Cloud Volumes"^].




== Tamaños de disco admitidos

En Azure, un agregado puede contener hasta 12 discos con el mismo tamaño y tipo.



=== Sistemas de un solo nodo

Los sistemas de un solo nodo usan discos gestionados de Azure. Se admiten los siguientes tamaños de disco:

[cols="3*"]
|===
| SSD premium | SSD estándar | HDD estándar 


 a| 
* 500 GIB
* 1 TIB
* 2 TIB
* 4 TIB
* 8 TIB
* 16 TIB
* 32 TIB

 a| 
* 100 GIB
* 500 GIB
* 1 TIB
* 2 TIB
* 4 TIB
* 8 TIB
* 16 TIB
* 32 TIB

 a| 
* 100 GIB
* 500 GIB
* 1 TIB
* 2 TIB
* 4 TIB
* 8 TIB
* 16 TIB
* 32 TIB


|===


=== Parejas de HA

Las parejas de HA utilizan Blobs de página Premium. Se admiten los siguientes tamaños de disco:

* 500 GIB
* 1 TIB
* 2 TIB
* 4 TIB
* 8 TIB

